sylius_twig_hooks:
    hooks:
        'sylius_admin.channel.update.content.form.sections.general':
            user_com_configuration:
                template: '@BitBagSyliusUserComPlugin/UserApiResource/_userComCredentials.html.twig'
                priority: 450
