sylius_twig_hooks:
    hooks:
        'sylius_shop.base#stylesheets':
            user_com_scripts:
                template: '@BitBagSyliusUserComPlugin/Scripts/_userComScripts.html.twig'
                priority: -100

        'sylius_shop.base.header':
            user_com_gtm:
                template: '@BitBagSyliusUserComPlugin/Scripts/_userComGTM.html.twig'
                priority: -100
