parameters:
    user_com.frontend_api_key: '%env(USER_COM_FRONTEND_API_KEY)%'
    user_com.encryption_key: '%env(USER_COM_ENCRYPTION_KEY)%'
    user_com.encryption_iv: '%env(USER_COM_ENCRYPTION_IV)%'

twig:
    globals:
        user_com_frontend_api_key: '%user_com.frontend_api_key%'

imports: 
    - { resource: "state_machine/*" }
    - { resource: "events.yaml" }
    - { resource: "monolog.yaml" }
    - { resource: "packages/*" }
